# Generated by Django 3.2.7 on 2021-11-29 01:43

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z,a-z,0-9,?./""-]+@(gmail|outlook|yahoo|icloud|gov|nic)+[.]+(com|org|net|gov|mil|biz|info|mobi|in|name|aero|jobs|museum|co)+$', 'Enter valid emil', 'Email should be valid and top level domain')])),
                ('password', models.CharField(max_length=500, validators=[django.core.validators.RegexValidator('^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!#%*?&]{6,20}$', 'Password should reach required pattern', '')])),
                ('uniqueId', models.CharField(max_length=100, unique=True)),
                ('token', models.CharField(max_length=500)),
                ('userHandle', models.CharField(default='null', max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('profileImg', models.CharField(max_length=500)),
                ('proffesion', models.CharField(max_length=100)),
                ('Branch', models.CharField(choices=[('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('Electricals', 'Electricals'), ('Computer Science', 'Computer Science')], max_length=50)),
                ('currentSem', models.CharField(max_length=50)),
                ('isActivated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('contactedTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseName', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationTitle', models.CharField(max_length=50)),
                ('relatedTo', models.CharField(max_length=50)),
                ('notificationDescription', models.TextField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('branchName', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('scheme', models.CharField(default=2018, max_length=4)),
                ('branchImage', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='branch/')),
                ('documentURL', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='branchSyllabus')),
            ],
        ),
        migrations.CreateModel(
            name='YearOrSem',
            fields=[
                ('yearOrSemName', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('user_slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='user', unique=True)),
                ('profile_picture', models.ImageField(blank=True, default='user_profiles/default.png', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='user_profiles')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, max_length=128, null=True)),
                ('usn', models.CharField(blank=True, max_length=20, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('github_profile', models.URLField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('facebook_profile', models.URLField(blank=True, null=True)),
                ('instagram_profile', models.URLField(blank=True, null=True)),
                ('twitter_profile', models.URLField(blank=True, null=True)),
                ('codeforces_handle', models.CharField(blank=True, max_length=20, null=True)),
                ('codechef_handle', models.CharField(blank=True, max_length=20, null=True)),
                ('leetcode_handle', models.CharField(blank=True, max_length=20, null=True)),
                ('hackerrank_handle', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=100)),
                ('subjectCode', models.CharField(blank=True, max_length=100, null=True)),
                ('documentURL', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='questionPapers')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
                ('yearOrSem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.yearorsem')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=100)),
                ('subjectCode', models.CharField(blank=True, max_length=100, null=True)),
                ('documentURL', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='notes')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
                ('yearOrSem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.yearorsem')),
            ],
        ),
    ]
