# Generated by Django 3.2.5 on 2021-07-21 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('contactedTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseName', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('branchName', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('scheme', models.CharField(default=2018, max_length=4)),
                ('branchImage', models.ImageField(upload_to='branch/')),
                ('documentURL', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearOrSem',
            fields=[
                ('yearOrSemName', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('profile_picture', models.ImageField(blank=True, default='user_profiles/default.png', upload_to='user_profiles')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, max_length=128, null=True)),
                ('usn', models.CharField(blank=True, max_length=20, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('github_profile', models.URLField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('facebook_profile', models.URLField(blank=True, null=True)),
                ('instagram_profile', models.URLField(blank=True, null=True)),
                ('twitter_profile', models.URLField(blank=True, null=True)),
                ('codeforces_handle', models.CharField(blank=True, max_length=20, null=True)),
                ('codechef_handle', models.CharField(blank=True, max_length=20, null=True)),
                ('leetcode_handle', models.CharField(blank=True, max_length=20, null=True)),
                ('hackerrank_handle', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=100)),
                ('subjectCode', models.CharField(blank=True, max_length=100, null=True)),
                ('documentURL', models.URLField(max_length=512, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
                ('yearOrSem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.yearorsem')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=100)),
                ('subjectCode', models.CharField(blank=True, max_length=100, null=True)),
                ('documentURL', models.URLField(max_length=512, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
                ('yearOrSem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.yearorsem')),
            ],
        ),
    ]
