# Generated by Django 3.2.4 on 2021-06-26 11:50

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=100, unique=True, validators=[backend.models.Accounts.validate_userEmail])),
                ('password', models.CharField(max_length=500, validators=[backend.models.Accounts.validate_password])),
                ('uniqueId', models.CharField(default='this', max_length=100, unique=True)),
                ('token', models.CharField(max_length=500)),
                ('userHandle', models.CharField(default='null', max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('profileImg', models.CharField(max_length=500)),
                ('proffesion', models.CharField(max_length=100)),
                ('Branch', models.CharField(choices=[('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('Electricals', 'Electricals'), ('Computer Science', 'Computer Science')], max_length=50)),
                ('currentSem', models.CharField(max_length=50)),
                ('isActivated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('contactedTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('branchName', models.CharField(choices=[('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('Electricals', 'Electricals'), ('Computer Science', 'Computer Science')], max_length=50, primary_key=True, serialize=False, unique=True)),
                ('scheme', models.CharField(default=2018, max_length=4)),
                ('branchImage', models.ImageField(default='branch/system.png', upload_to='branch/')),
            ],
        ),
    ]
