# Generated by Django 3.2.5 on 2021-07-21 23:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='user', unique=True),
        ),
    ]
