# Generated by Django 3.2.8 on 2021-10-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='oauth_profile',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
