# Generated by Django 3.2.7 on 2021-11-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(upload_to='team')),
                ('fullName', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=30)),
                ('bio', models.TextField(max_length=100)),
            ],
        ),
    ]
