# Generated by Django 3.2.8 on 2021-10-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_userprofile_oauth_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='oauth_profile',
        ),
    ]
