# Generated by Django 3.2.4 on 2021-06-30 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_course_notes_syllabus_yearorsem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='subjectCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='QuestionPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=100)),
                ('subjectCode', models.CharField(blank=True, max_length=100, null=True)),
                ('documentURL', models.URLField(max_length=512, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
                ('yearOrSem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.yearorsem')),
            ],
        ),
    ]
