# Generated by Django 3.2.7 on 2021-09-25 11:40

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_userprofile_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='branchImage',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='branch/'),
        ),
    ]
