# Generated by Django 3.2.5 on 2021-07-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('backend', '0003_auto_20210630_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user', verbose_name='user')),
                ('name', models.CharField(max_length=30)),
                ('bio', models.TextField(max_length=250)),
                ('birth_date', models.DateField()),
                ('profile_picture', models.ImageField(blank=True, default='user_profiles/default.png', upload_to='user_profiles')),
            ],
        ),
    ]
