# Generated by Django 3.2.4 on 2021-06-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210613_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='branchName',
            field=models.CharField(choices=[('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('Electricals', 'Electricals'), ('Computer Science', 'Computer Science')], max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
