# Generated by Django 3.2.7 on 2021-12-09 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211207_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='club_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.club'),
        ),
    ]
