# Generated by Django 3.2.4 on 2021-06-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210625_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseName', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearOrSem',
            fields=[
                ('yearOrSemName', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=100)),
                ('subjectCode', models.CharField(blank=True, max_length=20, null=True)),
                ('documentURL', models.URLField(max_length=512, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
                ('yearOrSem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.yearorsem')),
            ],
        ),
    ]
