# Generated by Django 3.2.7 on 2021-12-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_attendance_club_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='IccContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=100)),
                ('contest_time', models.DateTimeField()),
                ('contest_link', models.URLField(max_length=120)),
            ],
        ),
    ]
