# Generated by Django 3.2.4 on 2021-06-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_syllabus_branchname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='branchImage',
            field=models.ImageField(default='/branch/system.png', upload_to='branch/'),
        ),
    ]
