# Generated by Django 3.2.4 on 2021-06-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_syllabus_branchimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='branchImage',
            field=models.ImageField(default='system.png', upload_to='branch/'),
        ),
    ]
