# Generated by Django 3.2.5 on 2021-07-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210625_2120'),
        ('backend', '0005_auto_20210713_1719'),
    ]

    operations = [
    ]
