# Generated by Django 3.2.5 on 2021-07-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_merge_0005_auto_20210625_2120_0005_auto_20210713_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='documentURL',
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='branchImage',
            field=models.ImageField(default='branch/system.png', upload_to='branch/'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='branchName',
            field=models.CharField(choices=[('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('Electricals', 'Electricals'), ('Computer Science', 'Computer Science')], max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
