# Generated by Django 3.2.4 on 2021-06-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_syllabus_branchimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='documentURL',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='branchImage',
            field=models.ImageField(upload_to='branch/'),
        ),
    ]
