# Generated by Django 3.2.4 on 2021-06-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_syllabus_branchimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('uniqueId', models.CharField(max_length=100)),
                ('isActivated', models.BooleanField(default=False)),
            ],
        ),
    ]
