# Generated by Django 3.2.4 on 2021-06-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Branch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='currentSem',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='firstName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='lastName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='proffesion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='signup',
            name='profileImg',
            field=models.CharField(default='', max_length=500),
        ),
    ]
