# Generated by Django 3.2.4 on 2021-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210622_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Branch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='currentSem',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='firstName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='lastName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='proffesion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='profileImg',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
