# Generated by Django 3.2.4 on 2021-06-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210622_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='firstName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
