# Generated by Django 3.2.4 on 2021-06-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_signup_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
                ('uniqueId', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=500)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('profileImg', models.CharField(max_length=500)),
                ('proffesion', models.CharField(max_length=100)),
                ('Branch', models.CharField(choices=[('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('Electricals', 'Electricals'), ('Computer Science', 'Computer Science')], max_length=50)),
                ('currentSem', models.CharField(max_length=50)),
                ('isActivated', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
